[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "exandroidnativeemu"
version = "0.1.0"
description = "Improved version of AndroidNativeEmu"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "capstone>=5.0.6",
    "hexdump>=3.3",
    "keystone-engine>=0.9.2",
    "loguru>=0.7.3",
    "pyelftools>=0.32",
    "unicorn>=2.1.4",
    "pycryptodome>=3.20.0",
]
authors = [
  {name = "User", email = "user@example.com"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[tool.setuptools.packages.find]
include = ["androidemu*"]

[tool.setuptools.package-data]
androidemu = ["data/vfs/**/*", "data/emu_cfg/**/*"]

[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "ruff>=0.3.0",
    "mypy>=1.9.0",
]
